apiVersion: v1
kind: Pod
metadata:
  name: connectivity-test
spec:
  containers:
  - name: curl
    image: curlimages/curl:7.70.0
    command: ["sh", "-c", "while true; do curl -I https://google.com; sleep 60; done"]
